package org.rigorcore.caserecomp

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

class VerifiedSceneUnitTest {
    /** Generated by tests/test_verified_scene.py; parsing it proves cross-language binding parity. */
    private val fixtureText: String = listOf("../../fixtures", "../fixtures", "fixtures")
        .map { File(it, "synthetic-verified-scene.crscene") }
        .first { it.isFile }
        .readText(Charsets.UTF_8)

    private val proof = VerifiedSceneProofParser.parse(fixtureText)

    private fun scenario() = ScenarioV1(
        id = "synthetic-scene-proof", designWidth = 64, designHeight = 48,
        scenes = listOf(ScenarioSceneV1("room", 1, 2, listOf(ScenarioTargetV1("placeholder", GameRect(1f, 1f, 4f, 4f), 1)))),
    )

    private fun runtime(store: SessionStore = InMemorySessionStore(), gate: FlowGate? = null): GameRuntime {
        val played = proof.applyTo(scenario())
        return GameRuntime(played, DeterministicClock(), store, RecordingAudioPort(),
            flowGate = gate ?: VerifiedSceneGate(AllowAllFlowGate, listOf(proof)))
            .also { it.onCreate(); it.onStart(); it.onResume() }
    }

    /** View == design size, so screen coordinates are game coordinates (+0.5 = pixel centre). */
    private fun GameRuntime.tap(x: Int, y: Int): StepResult? =
        inputForTap(x + 0.5f, y + 0.5f, 64f, 48f)?.let(::dispatch)

    private fun mutate(change: (MutableMap<String, Any?>) -> Unit, rebind: Boolean = true): String {
        @Suppress("UNCHECKED_CAST")
        val root = (MiniJson.parse(fixtureText) as Map<String, Any?>).toMutableMap()
        change(root)
        if (rebind) {
            root.remove("binding_sha256")
            root["binding_sha256"] = sha256Hex(MiniJson.canonical(root))
        }
        return MiniJson.canonical(root)
    }

    @Test fun python_fixture_parses_with_identical_binding() {
        assertEquals("synthetic-scene-proof", proof.scenarioId)
        assertEquals("room", proof.sceneId)
        assertEquals(listOf("dot", "ring"), proof.targets.map { it.id })
        assertEquals(5, proof.counterStart)
        assertEquals(GameRect(25f, 25f, 35f, 35f), proof.acknowledgeRegion)
        assertEquals(VerifiedSceneProofParser.canonicalize(fixtureText), MiniJson.canonical(MiniJson.parse(fixtureText)) + "\n")
    }

    @Test fun ring_mask_hole_misses_and_edge_hits() {
        val ring = proof.targets.first { it.id == "ring" }.mask
        assertTrue(ring.contains(GamePoint(4.5f, 4.5f)))
        assertFalse(ring.contains(GamePoint(8.5f, 8.5f)))
        assertFalse(ring.contains(GamePoint(3.5f, 4.5f)))
        assertTrue(ring.contains(GamePoint(13.5f, 13.5f)))
        assertFalse(ring.contains(GamePoint(14.5f, 13.5f)))
    }

    @Test fun verified_scene_plays_to_acknowledge_and_locks() {
        val run = runtime()
        run.dispatch(Input.Start)
        run.dispatch(Input.EnterScene("room"))
        assertEquals(Screen.SCENE, run.session.screen)

        assertNull("miss inside ring hole", run.inputForTap(8.5f, 8.5f, 64f, 48f))
        assertEquals(EngineEvent.TargetFound("room", "ring"), run.tap(4, 4)!!.events.single())
        assertNull("found target is no longer clickable", run.inputForTap(4.5f, 4.5f, 64f, 48f))
        assertEquals(4, proof.counterAfter(run.session.found("room").size))

        val last = run.tap(41, 31)!!
        assertEquals(listOf(EngineEvent.TargetFound("room", "dot"), EngineEvent.SceneCompleted("room")), last.events)
        assertEquals(Screen.SCENE, run.session.screen)
        assertTrue(run.renderFrame().awaitingAcknowledge)
        assertEquals(3, proof.counterAfter(run.session.found("room").size))

        assertEquals(Screen.SCENE, run.dispatch(Input.BackToMap).session.screen)
        assertNull("only the dialog button acknowledges", run.inputForTap(5.5f, 5.5f, 64f, 48f))
        val ack = run.tap(30, 30)!!
        assertEquals(listOf(EngineEvent.LeftScene("room")), ack.events)
        assertEquals(Screen.MAP, run.session.screen)
        assertFalse(run.renderFrame().awaitingAcknowledge)

        assertEquals("completed scene is locked", Screen.MAP, run.dispatch(Input.EnterScene("room")).session.screen)
    }

    @Test fun found_targets_and_lock_survive_restart() {
        val store = InMemorySessionStore()
        val first = runtime(store)
        first.dispatch(Input.Start); first.dispatch(Input.EnterScene("room")); first.tap(4, 4)
        first.onPause(); first.onStop(); first.onDestroy()

        val second = runtime(store)
        assertEquals(Screen.SCENE, second.session.screen)
        assertEquals(setOf("ring"), second.session.found("room"))
        second.tap(41, 31); second.tap(30, 30)
        second.onPause(); second.onStop(); second.onDestroy()

        val third = runtime(store)
        assertEquals(Screen.MAP, third.session.screen)
        assertEquals(Screen.MAP, third.dispatch(Input.EnterScene("room")).session.screen)
    }

    @Test fun gate_blocks_finds_without_a_scene_proof_and_delegates_navigation() {
        val played = proof.applyTo(scenario())
        val noProof = GameRuntime(played, DeterministicClock(), InMemorySessionStore(),
            flowGate = VerifiedSceneGate(AllowAllFlowGate, emptyList())).also { it.onCreate(); it.onStart(); it.onResume() }
        noProof.dispatch(Input.Start); noProof.dispatch(Input.EnterScene("room"))
        assertEquals(Screen.SCENE, noProof.session.screen)
        assertTrue(noProof.dispatch(Input.FindObject("ring")).events.isEmpty())

        val denied = runtime(gate = VerifiedSceneGate(DenyAllFlowGate, listOf(proof)))
        assertEquals(Screen.MENU, denied.dispatch(Input.Start).session.screen)

        val gate = VerifiedSceneGate(AllowAllFlowGate, listOf(proof))
        val inScene = Session(Screen.SCENE, "room")
        assertFalse(gate.allow(inScene, Input.FindObject("other"), inScene.copy(foundByScene = mapOf("room" to setOf("other"))), 0))
        assertFalse(gate.allowRestored(Session(foundByScene = mapOf("room" to setOf("unknown")))))
        assertFalse(gate.allowRestored(Session(foundByScene = mapOf("elsewhere" to setOf("x")))))
    }

    @Test fun tampered_or_unbound_proofs_are_rejected() {
        val bad = listOf(
            mutate({ it["scene_id"] = "other" }, rebind = false),
            mutate({ it["binding_sha256"] = "0".repeat(64) }, rebind = false),
            mutate({ it["evidence_kind"] = "synthetic" }),
            mutate({ it["version"] = 2L }),
            mutate({ it["version"] = 1.0 }),
            mutate({ it["extra"] = 1L }),
            mutate({ it["rules"] = (it["rules"] as Map<*, *>) + ("miss_effect" to "penalty") }),
            mutate({ it["rules"] = (it["rules"] as Map<*, *>) + ("counter_start" to -1L) }),
            mutate({ it["targets"] = (it["targets"] as List<*>).reversed() }),
            mutate({ it["targets"] = listOf((it["targets"] as List<*>).first().let { t ->
                (t as Map<*, *>) + ("mask" to ((t["mask"] as Map<*, *>) + ("bits" to "4Q=="))) }) }),
            mutate({ it["evidence_chain"] = mapOf("observation_sha256" to "1".repeat(64)) }),
        )
        bad.forEach { text -> assertTrue(text, runCatching { VerifiedSceneProofParser.parse(text) }.isFailure) }
    }

    @Test fun apply_rejects_mismatched_scenarios() {
        assertTrue(runCatching { proof.applyTo(scenario().copy(id = "other")) }.isFailure)
        val other = scenario().copy(scenes = listOf(ScenarioSceneV1("elsewhere", 1, 2,
            listOf(ScenarioTargetV1("t", GameRect(1f, 1f, 2f, 2f), 1)))))
        assertTrue(runCatching { proof.applyTo(other) }.isFailure)
        val withEvent = scenario().copy(events = listOf(ScenarioEventV1("e", "target-found", "room", "placeholder")))
        assertTrue(runCatching { proof.applyTo(withEvent) }.isFailure)
        assertTrue(runCatching { VerifiedSceneGate(AllowAllFlowGate, listOf(proof, proof)) }.isFailure)
        assertTrue(runCatching { ScenarioSceneV1("s", 1, 1, listOf(ScenarioTargetV1("t", GameRect(0f, 0f, 1f, 1f), 0)),
            SceneCompletion.ACKNOWLEDGE_THEN_MAP) }.isFailure)
    }

    @Test fun legacy_return_to_map_scenes_are_unchanged() {
        val engine = Engine(Scenario("s", listOf(SceneDefinition("a", setOf("x")))))
        val inScene = Session(Screen.SCENE, "a")
        val done = engine.step(inScene, Input.FindObject("x"))
        assertEquals(Screen.COMPLETE, done.session.screen)
        assertFalse(engine.awaitingAcknowledge(done.session))
        assertEquals(inScene, engine.step(inScene, Input.Acknowledge).session)
    }
}
